global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Scout application metrics
  - job_name: 'scout'
    static_configs:
      - targets: ['scout:4050']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # PostgreSQL exporter (optional)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
    
  # Redis exporter (optional)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']