apiVersion: v1
kind: Secret
metadata:
  name: scout-secrets
type: Opaque
stringData:
  database-url: "postgres://scout:your-secure-postgres-password-here@postgres:5432/scout_prod"
  secret-key-base: "your-64-character-secret-key-base-here-for-production-security"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scout-config
data:
  PORT: "4050"
  MIX_ENV: "prod"
  HOST: "0.0.0.0"